In [2]:
# 배열 생성
import numpy as np
data1 = [0,1,2,3,4,5,6,7,8]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# 실수
data2 = [0, 1, 3, 5, 10, 0.25]
a2 = np.array(data2)
a2

array([ 0.  ,  1.  ,  3.  ,  5.  , 10.  ,  0.25])

In [10]:
np.array([0.5, 2, 6, 0.01])

array([0.5 , 2.  , 6.  , 0.01])

In [7]:
# 데이터 타입 확인
a1.dtype

dtype('int32')

In [8]:
a2.dtype

dtype('float64')

In [12]:
# 행렬형태의 배열 생성
np.array([[1, 2, 3], [4, 5, 6] ,[7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# 범위를 지정하여 배열 생성
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(1, 10) # 1부터 10미만

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(5) #0부터 5미만

array([0, 1, 2, 3, 4])

In [18]:
#2차원 배열 형태
np.arange(12).reshape(4, 3) #0부터 11까지의 숫자를 4행 3열의 행렬로 표현

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
#행렬 형태 묻기
b1 = np.arange(12).reshape(4, 3)
b1.shape

(4, 3)

In [4]:
b2 = np.arange(5)
b2

array([0, 1, 2, 3, 4])

In [5]:
b2.shape

(5,)

In [8]:
# 범위 지정 후 원하는 개수만큼 데이터 추출
np.linspace(1, 10, 10) #1이상 10이하의 숫자 중 10개 뽑아서

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [10]:
# 특별한 형태의 배열
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# 데이터 타입 변환 
# 문자열
np.array(['0.5', '0.24', '2', '3.14', '3.141592'])

array(['0.5', '0.24', '2', '3.14', '3.141592'], dtype='<U8')

In [17]:
# 실수로 변환
str1 = np.array(['0.5', '0.24', '2', '3.14', '3.141592'])
num1 = str1.astype(float)
num1

array([0.5     , 0.24    , 2.      , 3.14    , 3.141592])

In [18]:
str1.dtype

dtype('<U8')

In [19]:
num1.dtype

dtype('float64')

In [21]:
# 정수로 변환
str2 = np.array(['1', '2', '3', '4', '5'])
num2 = str2.astype(int)
num2

array([1, 2, 3, 4, 5])

In [23]:
str2.dtype

dtype('<U1')

In [24]:
num2.dtype

dtype('int32')

In [25]:
num_f3 = np.array([10, 20, 0.543, 5.67, 9.87])
num_i3 = num_f3.astype(int)
num_i3

array([10, 20,  0,  5,  9])

In [26]:
num_f3.dtype

dtype('float64')

In [27]:
num_i3.dtype

dtype('int32')

In [29]:
# 난수를 사용하여 배열 생성 random -> 0~1 사이의 값
np.random.rand(2,3)

array([[0.5226436 , 0.73211178, 0.77013334],
       [0.98250857, 0.96267065, 0.72701532]])

In [31]:
# 랜덤하게 1개의 값만 추출
np.random.rand() 

0.6111967261354871

In [33]:
# 원하는 개수만큼 벡터 생성
np.random.rand(4) 

array([0.40131189, 0.80302699, 0.51850644, 0.14078894])

In [35]:
# 3차원 생성
np.random.rand(2, 3, 4) # (3,4)행렬을 2개 생성

array([[[0.24968938, 0.22840518, 0.84976393, 0.73515695],
        [0.89850203, 0.09223491, 0.85368552, 0.46605657],
        [0.22881005, 0.83897259, 0.08831209, 0.0722949 ]],

       [[0.32326137, 0.7132613 , 0.02515691, 0.01696906],
        [0.75550512, 0.44477003, 0.68213817, 0.35900762],
        [0.51880185, 0.72652063, 0.28249888, 0.52568089]]])

In [37]:
# 정수형 난수 생성
np.random.randint(10, size=(4,4)) # 10미만의 수를 (4,4)행렬로 표현

array([[0, 0, 0, 2],
       [3, 3, 4, 0],
       [0, 0, 6, 7],
       [4, 0, 0, 7]])

In [40]:
np.random.randint(1, 40) # 1에서 40미만의 값 중 하나 추출

6

In [42]:
# 배열 연산
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [45]:
arr1 + arr2

array([11, 22, 33, 44])

In [47]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [48]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [49]:
arr2 * 2

array([2, 4, 6, 8])

In [50]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [51]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [53]:
arr1 >= 20

array([False,  True,  True,  True])

In [55]:
# 통계를 위한 연산
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [57]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [58]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [59]:
[arr3.max(), arr3.min()]

[4, 0]

In [60]:
[arr3.cumsum(), arr3.cumprod()]

[array([ 0,  1,  3,  6, 10], dtype=int32), array([0, 0, 0, 0, 0], dtype=int32)]

In [67]:
# 행렬 연산
A = np.array([1, 2, 3, 4]).reshape(2,2)
A

B = np.array([9, 8, 7, 6]).reshape(2, 2)
B

array([[9, 8],
       [7, 6]])

In [69]:
# 덧셈
A + B

array([[10, 10],
       [10, 10]])

In [71]:
# 뺄셈
B - A

array([[8, 6],
       [4, 2]])

In [74]:
# 곱셈 (앞의 행과 뒤의 열 개수가 동일해야 함)
A.dot(B)

array([[23, 20],
       [55, 48]])

In [77]:
np.dot(A, B)

array([[23, 20],
       [55, 48]])

In [78]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [79]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [3]:
# 배열 인덱싱
index1 = np.array([0, 10, 20, 30, 40, 50])
index1

array([ 0, 10, 20, 30, 40, 50])

In [6]:
index1[0] # 인덱스 위치 지정

0

In [7]:
index1[3]

30

In [9]:
# 배열 값 수정
index1[5] = 100
index1

array([  0,  10,  20,  30,  40, 100])

In [11]:
# 동시에 여러 개 추출
index1[[3, 4]]

array([30, 40])

In [12]:
# 행렬에서 데이터 선택
index2 = np.arange(10, 100, 10).reshape(3, 3)
index2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [13]:
index2[2, 2]

90

In [15]:
index2[2,2] = 100
index2

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80, 100]])

In [20]:
# 행 전체 수정
index2[1] = [12, 13, 14]
index2

array([[ 10,  20,  30],
       [ 12,  13,  14],
       [ 70,  80, 100]])

In [23]:
# 원하는 행렬 위치 값 여러개 추출
index2[[0, 2], [0, 1]] # (0,0)값과 (2,1)값이 추출됨

array([10, 80])

In [24]:
index = np.array([1, 2, 3, 4, 5, 6])

In [25]:
# 조건으로 데이터 추출
index[index > 3]

array([4, 5, 6])

In [26]:
index[(index % 2) == 0]

array([2, 4, 6])

In [27]:
# 배열의 슬라이싱
slice1 = np.array([0, 10, 20, 30, 40, 50])

In [30]:
slice1[1:4] # 인덱스, 슬라이싱의 마지막 값은 -> 미만 값

array([10, 20, 30])

In [31]:
slice1[:3]

array([ 0, 10, 20])

In [32]:
slice1[2:]

array([20, 30, 40, 50])

In [35]:
slice1[2:5] = np.array([23, 35, 45])
slice1

array([ 0, 10, 23, 35, 45, 50])

In [36]:
slice1[3:6] = 60
slice1

array([ 0, 10, 23, 60, 60, 60])

In [37]:
slice2 = np.arange(10, 100, 10).reshape(3, 3)
slice2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [38]:
slice2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [39]:
slice2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [43]:
slice2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
slice2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])