In [3]:
# 실습테스트 1
import numpy as np
x = np.random.rand(5,6)
x = x.round(3) * 100
arr1 = np.array(x)
arr1

array([[13. , 94.2, 40. , 99.6, 54.6, 84.2],
       [ 9.4, 87.7, 98.7,  0.9, 12.4, 19.7],
       [29.7, 41.3, 38.4, 51.8, 81. , 78.3],
       [81. , 71.8, 57.1, 14.4, 99.6, 55.7],
       [34.2, 59. , 85.3, 49.1, 57.5, 10.2]])

In [12]:
# 최댓값
arr1.max()

99.6

In [13]:
# 최솟값
arr1.min()

0.8999999999999999

In [14]:
# 평균
arr1.mean()

53.65999999999999

In [15]:
# 표준편차
arr1.std()

30.390619166666102

In [16]:
# 분산
arr1.var()

923.5897333333331

In [22]:
# 실습테스트 2
arr1 = np.arange(0, 15).reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
# 값 7 인덱싱
arr1[1, 2]

7

In [33]:
# 값 14 인덱싱
arr1[2, 4]

14

In [34]:
# 배열 [6, 7] 슬라이싱
arr1[1, 1:3]

array([6, 7])

In [35]:
# 배열 [7, 12] 슬라이싱
arr1[1:3, 2]

array([ 7, 12])

In [38]:
# 배열 [[3, 4], [8, 9]] 슬라이싱
arr1[:2, 3:5]

array([[3, 4],
       [8, 9]])

In [57]:
# 실습테스트 3 - 1
def intersection(a, b):
    c = []
    for i in a:
        if i in b:
            c.append(i)
        c.sort()
    return c

In [58]:
# 실습테스트 3 - 2
import numpy as np
def random_exclusive(low, high, how_many):
    number = []
    while how_many > 0:
        a = np.random.randint(low, high)
        if a not in number:
            number.append(a)
        else: how_many += 1
        how_many -= 1
    return number

random_exclusive(1, 31, 10)

[15, 29, 12, 26, 14, 24, 20, 19, 13, 2]

In [65]:
# 실습테스트 3 - 3
low = 1
high = 31
how_many = 10
A = random_exclusive(low, high, how_many)
B = random_exclusive(low, high, how_many)
C = intersection(A, B)

print("A그룹의 난수는 : {}".format(A))
print("B그룹의 난수는 : {}".format(B))
print("A, B그룹의 교집합은 : {}".format(C))

A그룹의 난수는 : [7, 19, 15, 3, 9, 13, 16, 28, 11, 5]
B그룹의 난수는 : [4, 29, 25, 20, 21, 27, 3, 13, 9, 5]
A, B그룹의 교집합은 : [3, 5, 9, 13]
